os: linux
dist: focal
cache: pip
services:
  - redis
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - CELERY=4
  - CELERY=5
before_install:
  - pip install --upgrade pip
  - pip install poetry
install:
  - poetry install -v
  - if [[ $CELERY == "4" ]]; then pip install "celery>=4, <5"; fi
script: python -m pytest
